spring:
   application:
      name: spirng-boot-rabbitmq-receice
   rabbitmq:
      host: 120.77.214.1
      port: 5672
      username: admin
      password: admin
server:
   port: 8081
test:
   mq:
      exchange: testExchange
      routingKey: testKey