spring:
   application:
      name: spirng-boot-rabbitmq-receice
   rabbitmq:
      host: 10.1.2.201
      port: 5672
      username: admin
      password: admin
server:
   port: 8081
mq:
   emp:
      exchange: eebo.iam.change_emp
      routingKey: eebo.iam.addOrUpdate_emp_key